spring.application.name=save-pocket

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:${MYSQL_PORT:3308}/${MYSQL_DATABASE:save-pocket}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.session.store-type=redis
spring.session.timeout=${SESSION_TIMEOUT:30m}
spring.session.redis.namespace=${SESSION_NAMESPACE:save-pocket:session}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

naver.api.client-id=${NAVER_CLIENT_ID:}
naver.api.client-secret=${NAVER_CLIENT_SECRET:}
naver.api.shopping-url=${NAVER_SHOPPING_API_PATH:/v1/search/shop.json}
