spring.application.name=save-pocket

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:${MYSQL_PORT:3308}/${MYSQL_DATABASE:save-pocket}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
